---

base_paths:
  bronze: "/mnt/bronze"
  silver: "/mnt/silver"
  gold: "/mnt/gold"

# Dataframes

reference_month:
  columns:
    - name: reference_month
      type: StringType()
      nullable: false

brands:
  columns:
    - name: brand
      type: StringType()
      nullable: false

url: https://veiculos.fipe.org.br/

xpaths:
  xpath_search_car : //a[@data-slug='carro' and @data-action='veiculos']
  xpath_bt_month_year : //*[@id="selectTabelaReferenciacarro"]
  xpath_bt_brand : //*[@id="selectMarcacarro"]
  xpath_bt_model : //*[@id="selectAnoModelocarro"]
  xpath_bt_year_fuel : //*[@id="selectAnocarro"]
  xpath_bt_search : //a[@id="buttonPesquisarcarro"]
